name: Build Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Install requirements
      run: pip install requests pyinstaller

    - name: Build the project for Windows
      if: runner.os == 'Windows'
      run: pyinstaller -F --add-data "static;static" main.py
    
    - name: Build the project for Mac
      if: runner.os == 'macOS'
      run: pyinstaller -F --add-data "static:static" main.py

    - name: Build the project for Linux
      if: runner.os == 'Linux'
      run: pyinstaller -F --add-data "static:static" main.py

    - uses: actions/upload-artifact@v2
      with:
        name: Build ${{ runner.os }}
        path: dist


